// SPDX-License-Identifier: Unlicense

#include "godot_cpp/core/class_db.hpp"

#include "GDExtensionTemplate.h"
#include "Version.h"

/// @file
/// GDExtensionTemplate example implementation.

// Example of how to use GDEXTENSIONTEMPLATE_VERSION_CHECK() for version checking
#if GDEXTENSIONTEMPLATE_VERSION > GDEXTENSIONTEMPLATE_VERSION_CHECK( 2, 1, 0 )
constexpr int DECLARE_SOMETHING = 42;
#endif

/*!
@brief Get the version string for this extension.

@details
The version string is generated by cmake using src/Version.h.in.

It uses the form "<project name> <last tag>-<# commits since last tag>-<short commit hash>".
If there are no commits since the last tag, only the tag is shown.

@return The version string (e.g. "Foo v1.2.3-gdedbd01").
*/
godot::String GDExtensionTemplate::version()
{
    return VersionInfo::VERSION_STR.data();
}

/// Bind our methods so GDScript can access them.
void GDExtensionTemplate::_bind_methods()
{
    godot::ClassDB::bind_static_method( "GDExtensionTemplate", godot::D_METHOD( "version" ),
                                        &GDExtensionTemplate::version );
}
